Sc cl functions
HomoSimulo/NFT-TD pull request #1
Opened 2023-05-23 11:21 UTC by Briojas

Added the contracts and js-scripts needed for calling Chainlink Functions. Configuration of the contracts to Chainlink Function subscriptions will be managed by the separate hardhat repo found here: https://github.com/smartcontractkit/functions-hardhat-starter-kit 

Functions contracts successfully compile and deploy to Sepolia. Subscriptions are successfully created via the hardhat starter kit.

2023-05-24 05:04 UTC, josiahlund requested changes

2023-05-24 05:04 UTC, josiahlund commented on smart-contracts/contracts/AutomatedFunctionsConsumer.sol
> + * @notice NOT FOR PRODUCTION USE
Was this from a template? I imagine we want to remove or revise these comment lines.

```suggestion
```

2023-05-24 05:04 UTC, josiahlund commented on smart-contracts/contracts/BeOurPest.sol
Some generic AI feedback on improving the readability of this file:

- Use more descriptive comments: Ensure that each function and complex operation in your code has an accompanying comment explaining what it does. This is important not just for other developers who might interact with your code, but also for your future self.

- Refactor large functions: Functions like performUpkeep and checkUpkeep could be refactored into smaller, more manageable functions. This would make it easier to understand and test individual components of your code.

- Group related variables: Instead of having a number of individual variables, consider grouping related variables into structs. For example, you could have a struct to group all timestamp-related variables.

- Consider using enumerations for states: Rather than representing states as string, consider using an enumeration to represent the different states. Enumerations are easier to reason about and less prone to errors from typos.

- Consistent naming convention: Ensure you are following a consistent naming convention throughout your code. It appears that you're using snake_case for your variable and function names which is common in Solidity. However, be consistent. For instance, you have job_id_pubsub_int and queue_fee both as instance variables, one uses abbreviation, the other does not.

- Avoid deeply nested if-else statements: In your performUpkeep function, you've nested several if-else statements. It would be cleaner and more readable to avoid this where possible, perhaps by using early returns or breaking up the function.

- Event Names: Event names are typically in PascalCase according to Solidity's style guide. For example, submission_ticket should be SubmissionTicket.

- Use modifiers where appropriate: Modifiers can be used to simplify functions and improve readability. For example, you could create a modifier to check if upkeep is needed in the performUpkeep function.

- Document struct fields: For complex structs like Submission, Queue, etc., adding comments to each field can clarify their purpose and make the code more accessible to others.

- Reduce complexity of code: Some of the operations, like iterator_skip_deleted and iterator_find_next_deleted, could potentially be simplified. Review these parts and consider if there are easier ways to achieve the same functionality.

2023-05-24 05:04 UTC, josiahlund commented on smart-contracts/contracts/BeOurPest.sol
> +        }
I try not to write daisy-chained else if's like this. When I see this pattern, I generally look to implement a dictionary, or in solidity, a "mapping". One possible change that I think would make this code more readable/maintainable in the long term is to define state transitions mapping at the contract level:

```sol
mapping(States => States) stateTransitions;

constructor() public {
    stateTransitions[States.READY] = States.EXECUTING;
    stateTransitions[States.EXECUTING] = States.EXECUTED;
    stateTransitions[States.EXECUTED] = States.COLLECTING;
    stateTransitions[States.COLLECTING] = States.COLLECTED;
    stateTransitions[States.COLLECTED] = States.READY;
}

// Your update_state function would then be simplified:
function update_state(Queue storage self) internal {
    self.state = stateTransitions[self.state];
}
```

2023-05-24 05:04 UTC, josiahlund commented on smart-contracts/contracts/BeOurPest.sol
> +    }
Using the same logic applied in `update_state()`, this could be refactored to improve readability.

```sol
mapping(States => function(Queue storage) internal) stateActions;

// In your constructor or an initializer function, you would setup the actions:
constructor() public {
    stateActions[States.READY] = readyAction;
    stateActions[States.EXECUTING] = executingAction;
    stateActions[States.EXECUTED] = executedAction;
    stateActions[States.COLLECTING] = collectingAction;
    stateActions[States.COLLECTED] = collectedAction;
}

// The specific actions for each state:
function readyAction(Queue storage self) internal { /* implementation... */ }
function executingAction(Queue storage self) internal { /* implementation... */ }
function executedAction(Queue storage self) internal { /* implementation... */ }
function collectingAction(Queue storage self) internal { /* implementation... */ }
function collectedAction(Queue storage self) internal { /* implementation... */ }

// And then in your performUpkeep function you would do:
function performUpkeep(Queue storage self) internal {
    stateActions[self.state](self);
    update_state(self);
}
```

2023-05-24 05:04 UTC, josiahlund commented on smart-contracts/contracts/CIDProcessorQueue.sol
> +    }
From a first glance at your code, it appears that the functions iterator_skip_deleted and iterator_find_next_deleted are quite similar. They both iterate through self.keys, checking the deleted field until they find a key index that satisfies a certain condition. These functions could be combined into one, taking a function parameter that defines the condition to be checked.

2023-05-24 05:04 UTC, josiahlund commented on smart-contracts/contracts/CIDProcessorQueue.sol
> +    }
The join function seems to be doing a lot of work. It would be easier to understand if it was broken down into smaller functions each with a single responsibility. Here's how it might be refactored:

```suggestion
    function join(Queue storage self, string calldata cid) internal {
        uint key = self.tickets.next_submission_key;
        self.tickets.num_tickets ++;
        initializeSubmission(self, key, cid);
        handleExistingKey(self, key);
        set_next_sub_key(self);
    }

    function initializeSubmission(Queue storage self, uint key, string calldata cid) internal {
        self.data[key].ticket = self.tickets.num_tickets;
        self.data[key].cid = cid;
        self.data[key].state = State.READY;
    }

    function handleExistingKey(Queue storage self, uint key) internal {
        uint key_index = self.data[key].key_index;
        if (key_index > 0) { //checks if key already existed, and was overwritten
            self.keys[key_index].deleted = false; //a deleted Submission overwritten should not be marked deleted
        } else { //if key didn't exist, the queue array has grown
            addToKeys(self, key);
        }
    }

    function addToKeys(Queue storage self, uint key) internal {
        uint key_index = self.keys.length;
        self.keys.push();
        self.data[key].key_index = key_index + 1;
        self.keys[key_index].key = key;
    }
```

2023-05-24 05:04 UTC, josiahlund commented on smart-contracts/contracts/CIDProcessorQueue.sol
> +    }
The function `find_ticket_key()` is not always returning a value. If the ticket is not found, goal_key would be uninitialized and might produce undefined behavior. You could initialize goal_key to a special value, or refactor the function to indicate if the key was found or not.

2023-05-24 05:04 UTC, josiahlund commented on smart-contracts/contracts/CIDProcessorQueue.sol
> +    }
The function `set_next_sub_key()` has a check `if(self.keys.length < 0)`. Since `self.keys.length` is of type uint (which can't be negative), this condition will never be true. You may want to remove or revise this check.

2023-05-24 05:04 UTC, josiahlund commented on smart-contracts/contracts/dev/AuthorizedReceiver.sol
> +  }
A potential area of improvement is regarding setAuthorizedSenders function:

Loop Optimization: You're currently removing all existing authorized senders and then adding the new ones. If the new set of senders has some overlap with the old set, you're doing unnecessary operations. Consider using an approach that only removes the senders that are not in the new list and only adds the senders that are not in the old list.

An approach to optimize the setAuthorizedSenders function could be:

Iterate over the new list of senders and add each sender to the s_authorizedSenders set. Keep track of which senders were added.

Iterate over the old list of senders, and for each sender, check if it was added in the previous step. If not, remove it from the s_authorizedSenders set.

Update the s_authorizedSendersList variable to point to the new list of senders.

Here's an example of how that might look:

```sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.6;

// (existing import statements)

abstract contract AuthorizedReceiver is AuthorizedReceiverInterface {
  // (existing variable declarations)

  function setAuthorizedSenders(address[] calldata senders) external override validateAuthorizedSenderSetter {
    if (senders.length == 0) {
      revert EmptySendersList();
    }

    // Create a temporary set to keep track of the new authorized senders
    EnumerableSet.AddressSet memory newSendersSet;
    for (uint256 i = 0; i < senders.length; i++) {
      // Check for zero address
      require(senders[i] != address(0), "Invalid address in senders list");
      newSendersSet.add(senders[i]);
    }

    // Add new senders to s_authorizedSenders and keep track of those who were added
    for (uint256 i = 0; i < senders.length; i++) {
      s_authorizedSenders.add(senders[i]);
    }

    // Remove senders from s_authorizedSenders who are not in the new list
    for (uint256 i = 0; i < s_authorizedSendersList.length; i++) {
      if (!newSendersSet.contains(s_authorizedSendersList[i])) {
        s_authorizedSenders.remove(s_authorizedSendersList[i]);
      }
    }

    // Update the authorized senders list
    s_authorizedSendersList = senders;
    emit AuthorizedSendersChanged(senders, msg.sender);
  }

  // (existing functions and modifiers)
}
```

Note: The temporary newSendersSet is used to efficiently check if a sender is in the new list of senders. This code also adds a check to prevent zero-addresses from being added to the list of authorized senders. Remember to test this code thoroughly to ensure it behaves as expected.

Lastly, please note that this is a naive approach for the optimization and it still has a linear time complexity. Depending on the size of your senders array and frequency of the setAuthorizedSenders call, you may need to think about gas costs and consider other techniques like batching to handle large arrays.

2023-05-24 05:04 UTC, josiahlund commented on smart-contracts/contracts/dev/functions/AuthorizedOriginReceiverUpgradeable.sol
This contract is using tx.origin instead of msg.sender to identify the origin of the transactions, which is generally discouraged because it can make contracts vulnerable to attacks. Consider the implications carefully before using tx.origin in your contracts.

2023-05-24 05:04 UTC, josiahlund commented on smart-contracts/contracts/dev/functions/Functions.sol
> +    if (bytes(source).length == 0) revert EmptySource();
Use require instead of if-revert: You're using an if-statement with a revert in initializeRequest function. Instead, you could use the require function, which is more idiomatic in Solidity for checks that should revert if they fail.

Here's how the code could look:

```suggestion
    require(bytes(source).length != 0, "EmptySource");
```

2023-05-24 05:04 UTC, josiahlund commented on smart-contracts/contracts/dev/functions/FunctionsClient.sol
> +  }
In the `setOracle()` function, there is no check if the provided oracle address is a zero address. It's a good practice to check for a zero address before assignment, as it might lead to inadvertent loss of funds or control if not intended.

2023-05-24 05:04 UTC, josiahlund commented on smart-contracts/contracts/dev/functions/FunctionsClient.sol
### Abstraction of common functionality
You can create a separate function for encoding requests and returning their IDs. This will reduce code duplication and make the code easier to read and maintain.

Currently, you are encoding the request and getting the requestId within the sendRequest function. You could abstract this out into a separate function like getRequestId:

```sol
  function getRequestId(
    Functions.Request memory req,
    uint64 subscriptionId,
    uint32 gasLimit
  ) internal view returns (bytes32) {
    bytes32 requestId = s_oracle.sendRequest(subscriptionId, Functions.encodeCBOR(req), gasLimit);
    return requestId;
  }
```

Then, you could use this function in sendRequest:

```sol
  function sendRequest(
    Functions.Request memory req,
    uint64 subscriptionId,
    uint32 gasLimit
  ) internal returns (bytes32) {
    bytes32 requestId = getRequestId(req, subscriptionId, gasLimit);
    s_pendingRequests[requestId] = s_oracle.getRegistry();
    emit RequestSent(requestId);
    return requestId;
  }
```

### Use events for tracking
It may be beneficial to emit events for significant state changes like changing the oracle. This can make it easier to track and audit the contract's operation.

Currently, there are events for when a request is sent and fulfilled. You could also add events for significant state changes, like when the Oracle address is changed. For example:

```sol
event OracleChanged(address indexed newOracle);
```

Then, within the setOracle function, emit the event after the new Oracle is set:

```sol
  function setOracle(address oracle) internal {
    require(oracle != address(0), "Oracle address cannot be 0");
    s_oracle = FunctionsOracleInterface(oracle);
    emit OracleChanged(oracle);
  }
```

This would allow you to track when the Oracle address was changed and to what new address.

2023-05-24 05:04 UTC, josiahlund commented on smart-contracts/contracts/dev/ocr2/OCR2Base.sol
> +    }
Gas Optimization: There are quite a few areas where gas optimization could be done. For example, in the setConfig function, there is a loop that deletes the old signer and transmitter addresses. Instead of deleting each element one by one, you can reset the entire array once by just setting its length to 0.

2023-05-24 05:04 UTC, josiahlund commented on smart-contracts/contracts/dev/ocr2/OCR2BaseUpgradeable.sol
See comment in OCR2Base.sol

2023-05-24 11:09 UTC, Briojas commented on smart-contracts/contracts/BeOurPest.sol
> +        }
I like the update. But, the "BeOurPest.sol" is actually a reference contract from an old project I'm using to build this project's contract. I refactored this code already in the new "CIDProcessorQueue.sol" contract. I forgot to remove the reference contract; removing now.

2023-05-24 11:19 UTC, Briojas commented on smart-contracts/contracts/BeOurPest.sol
> +    }
I haven't actually worked this update for our current contract yet, but this is absolutely how I'll write it now. But yeah this is that old referential contract I accidentally left in, which is annoying. Sorry. But this refactor will actually be super useful.

2023-05-24 11:42 UTC, Briojas commented on smart-contracts/contracts/CIDProcessorQueue.sol
> +    }
Updated! Haven't tested yet.

2023-05-24 11:44 UTC, Briojas commented on smart-contracts/contracts/CIDProcessorQueue.sol
> +    }
Good call. I'll return 0 for now, but the better solution would be to indicate a key isn't found. May rework later.

2023-05-24 11:53 UTC, Briojas commented on smart-contracts/contracts/CIDProcessorQueue.sol
> +    }
No idea what I was doing here. I think originally I had some janky logic figured out where keys WASN'T a uint, and the empty array would return a -1? lol, not sure. I hardset the first 'next_submission_key' on initiatie(), so it should be resolved. Removing useless condition.

2023-05-24 22:16 UTC, Briojas commented on smart-contracts/contracts/CIDProcessorQueue.sol
> +    }
Great idea. I didn't refactor the submission details for now, but might just end up doing that anyway. Would make it cleaner for reusing this library in the future.

2023-05-24 22:19 UTC, Briojas commented on smart-contracts/contracts/AutomatedFunctionsConsumer.sol
> + * @notice NOT FOR PRODUCTION USE
I agree, yeah basically a template. This contract is really just for reference, as I'll be building our own contract seperately. Probably should have just started that here, but I'll just start it in the next contracts-related branch.

2023-05-24 22:30 UTC, Briojas commented on smart-contracts/contracts/BeOurPest.sol
I'll have to get back to some of these

2023-05-24 22:32 UTC, Briojas commented on smart-contracts/contracts/dev/functions/Functions.sol
> +    if (bytes(source).length == 0) revert EmptySource();
This came directly from Chainlink, but cool to see these improvements. I'm going to stick to their source code for now, but joining their github org and suggesting these updates may be a cool idea.

2023-05-24 22:33 UTC, Briojas commented on smart-contracts/contracts/dev/functions/FunctionsClient.sol
This came directly from Chainlink, but cool to see these improvements. I'm going to stick to their source code for now, but joining their github org and suggesting these updates may be a cool idea.

2023-05-24 22:33 UTC, Briojas commented on smart-contracts/contracts/dev/ocr2/OCR2Base.sol
> +    }
This came directly from Chainlink, but cool to see these improvements. I'm going to stick to their source code for now, but joining their github org and suggesting these updates may be a cool idea.

2023-05-24 22:33 UTC, Briojas commented on smart-contracts/contracts/dev/ocr2/OCR2BaseUpgradeable.sol
This came directly from Chainlink, but cool to see these improvements. I'm going to stick to their source code for now, but joining their github org and suggesting these updates may be a cool idea.

2023-05-24 22:33 UTC, Briojas commented on smart-contracts/contracts/dev/functions/FunctionsClient.sol
> +  }
This came directly from Chainlink, but cool to see these improvements. I'm going to stick to their source code for now, but joining their github org and suggesting these updates may be a cool idea.

2023-05-24 22:34 UTC, Briojas commented on smart-contracts/contracts/dev/AuthorizedReceiver.sol
> +  }
This came directly from Chainlink, but cool to see these improvements. I'm going to stick to their source code for now, but joining their github org and suggesting these updates may be a cool idea.

2023-05-24 22:35 UTC, Briojas commented on smart-contracts/contracts/dev/functions/AuthorizedOriginReceiverUpgradeable.sol
This came directly from Chainlink, but cool to see these improvements. I'm going to stick to their source code for now, but joining their github org and suggesting these updates may be a cool idea.

2023-05-25 13:33 UTC, josiahlund approved these changes

2023-05-25 13:34 UTC, merged